### ISSUE TITLE
question: Is it possible to have temporary addresses with the TMTP protocol?

### ISSUE THREAD

**Issue by ghost** [networkimprov/mnm#11]
Hi all!

I have an interesting question, at least I find it initially interesting. Is it possible to have temporary messages with the TMTP protocol?

#### 1. Context of the question
1. One of the things I don't really like about email is that email doesn't support temporary messages. Sometimes you access a website and need to register for it. However, this site keeps sending you a lot of messages. Some messages are spam, programmed. An alternative to this, it is very common to use temporary emails. 
2. With a temporary email, you can register on one or more sites without necessarily committing to receive notifications.
3. Because... bearing in mind, that after a temporary email is created - it is unique after some time. And the messages you receive by email are deleted as well.

#### 2. Why is this interesting, relevant?
1. This might be interesting for better security and privacy for users, given that users could have temporary messages to be deleted on the server. What prevents or can prevent if the server is compromised that users have messages read by anyone.
2. Also, this prevents the server from being overloaded... I think of this idea, because as the messages are being deleted it takes up more processing space on the server side.
3. Perhaps this is innovative, as most emails do not have this feature. Generally, deleting messages is sometimes manual. That way everything would be more automatic and customizable, which would make it much easier for users and the system itself, the server itself.

#### 3. Notes
1. We can cite as an example the tempmail site that deletes messages after 24 hours.
2. There is pastebin where everything that is stored can be deleted according to a time that the user himself defines.
3. When I talk about pastebin or tempmail, I'm just referencing these two services or software as a bibliographic reference here,
4. My intention is not to promote them, but to analyze the features that both software have to see if it makes sense for the TMTP protocol to support such features as for example: temporary messages or messages defined for a while
5. I would be happy to know if this has already been thought or not, or if the idea I put here is good or bad
6. This is a question and not a feature request.

#### 4. References
1. https://temp-mail.org/en/
2. https://pastebin.com/

**Comment by networkimprov** [comment]
I think you're asking about multiple (possibly temporary) addresses linked to a single email account.

TMTP assumes that you have many separate accounts, each linked to a specific site. See the demo for an example:
https://mnmnotmail.org/w/service-demo.html?Chox%20HQ

TMTP sites where you do not have an account cannot reach you at all. You can close your account on a site at any time, and never receive messages from it again. (This is not yet implemented in the client app.)

You can also resign from any specific message thread, or block any specific member from sending you more messages.

And you can create multiple "aliases" to your account ID on a TMTP site (if the site allows that), Typically you would not add temporary, aliases, as you have the methods mentioned above to stop ppl from contacting you. But you could "close" an alias to prevent anyone else from using it to initiate contact with you.

I hope that answers your questions!

**Comment by ghost** [comment]
@networkimprov Hi! thank you for feedback! Please close this issue, everything has been resolved - you clarified all doubts.
