### ISSUE TITLE
question: is TMTP federated like ActivityPub?

### ISSUE THREAD

**Issue by ghost** [networkimprov/mnm#14]
Hey there! I want to know if mnmnotmail is something federative like ActivityPub. mnmnotmail is something federative like ActivityPub?

**Comment by networkimprov** [comment]
TMTP is not federated; it works something like the web -- a client connects directly to each service where the user has an account. Federation in email is an artifact of the era (early 80s) when email was invented, when the Internet's topology & population were dramatically different. This is discussed further in the faq: https://mnmnotmail.org/faq.html

A TMTP service could serve as a proxy client in cases where a proxy is necessary, e.g. logging traffic between your employees and your suppliers' TMTP sites.

**Comment by ghost** [comment]
Hi networkimprov.

> TMTP is not federated; it works something like the web -- a client connects directly to each service where the user has an account. Federation in email is an artifact of the era (early 80s) when email was invented, when the Internet's topology & population were dramatically different. This is discussed further in the faq: https://mnmnotmail.org/faq.html
> A TMTP service could serve as a proxy client in cases where a proxy is necessary, e.g. logging traffic between your employees and your suppliers' TMTP sites.

Thanks for all the information shared. I will close this issue, you clarified all my doubts.

*Have a great day, and thank you for your patience in answering my questions.*
